### ISSUE TITLE
Unstable order on search

### ISSUE THREAD

**Issue by epidemian** [seppo0010/acrossoverepisode.com#3]
Search results' order doesn't seem to be stable:

https://user-images.githubusercontent.com/722544/173212343-af7ec116-4dd4-449d-95fa-43852e33f447.mp4

This was a bit unexpected, especially when typing a space after the search term changed the order of the search results.

**Comment by seppo0010** [comment]
This was intentionally added... I understand it is unexpected though, but I thought it'd be a (bad) way for people to find more captions. I can just revert it.

https://github.com/seppo0010/acrossoverepisode.com/commit/19b982720f33fc0edfda31a61fd4a714c63f4255
